### ISSUE TITLE
Suggestion: Instead of public S3 bucket use CloudFront distribution

### ISSUE THREAD

**Issue by frumania** [unfor19/aws-build-badges#7]
Hi,

i have just deployed your solution yesterday and it really works well!

A minor thing, being an AWS employee, where public S3 buckets are not allowed ;):
I'd suggest switching to a private bucket and use a CloudFront distribution in front.
Not sure if you automate this easily, but maybe worth mentioning.

Again, thanks for your work!

**Comment by unfor19** [comment]
@frumania I'm glad to hear that it works, thank you for your input!

Regarding the S3 bucket which serves the resources; it's defined in the [CloudFormation template](https://github.com/unfor19/aws-build-badges/blob/master/aws_build_badges_cf_template.yml#L259-L277)

Line 259
```yml
    # Images Bucket
    BuildBadgesImagesBucket:
        Type: 'AWS::S3::Bucket'
        DeletionPolicy: Retain
        Properties:
            BucketName: !Sub '${AppName}-badges-images-${Stage}'
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
            CorsConfiguration:
                CorsRules:
                    - AllowedHeaders:
                          - '*'
                      AllowedMethods:
                          - GET
                          - HEAD
                      AllowedOrigins:
                          - 'https://github.com'
                          - 'https://www.github.com'
                      MaxAge: 90
```

If you want to make it private, just play with the above properties of this bucket.

Alternatives for using a private S3 bucket
1. Create an API Gateway and a Lambda Function which is allowed to fetch the data from the private S3 bucket
1. I think that putting a CDN in front of the S3 bucket (such as CloudFront) would be no good; you'll have to invalidate the cache of this CloudFront distribution after each time that this app generates a badge

If you feel that the 1st alternative (API Gateway + Lambda Function) can work for you, let me know and I'll add another folder with this kind of application
